name: Check PR Template

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    name: Check
    runs-on:
      group: Template
    permissions:
      contents: read
    steps:
      - name: Clone paddle
        uses: actions/checkout@v4

      - name: Check PR Template
        env:
          AGILE_PULL_ID: ${{ github.event.pull_request.number }}
          AGILE_COMPILE_BRANCH: ${{ github.base_ref }}
          AGILE_CHECKIN_AUTHOR: ${{ github.event.pull_request.user.login }}
          method: check_pr
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 tools/CheckPRTemplate.py; EXCODE=$?
          echo "EXCODE: $EXCODE"
          echo "ipipe_log_param_EXCODE: $EXCODE"
          set +x
          if [[ "$EXCODE" != "0" ]];then
            echo -e "######################################################"
            echo -e "If you encounter a situation where the PR template does not match the error message, please use the following link to update your PR: [  https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/.github/PULL_REQUEST_TEMPLATE.md ]"
            echo -e "##ReferenceDocumentation: ##"
            echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/PULL-REQUEST-TEMPLATE--REFERENCE ]"
            echo -e "[ https://github.com/PaddlePaddle/Paddle/wiki/paddle_ci_manual ]"
            echo -e "######################################################"
          fi
          [[ $EXCODE -eq 0 ]] && {
            export method=$method
            echo $method
            set +x
            source ~/.icafe
            wget -q --no-check-certificate https://paddle-qa.bj.bcebos.com/baidu/cloud/modify_icafe.py
            set -x
            python3 modify_icafe.py
          }
